runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
network:
  forwarded_ports:
    - 1025/tcp
runtime_config:
  python_version: 3

#[START gae_flex_storage_yaml]
env_variables:
    CLOUD_STORAGE_BUCKET: roboticsaiapp_upload
#[END gae_flex_storage_yaml]